### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by stefanosala**

### CODE REVIEW

**Comment by RickCraig** [comment]
Hmm, I think we might need to release at least a minor (maybe a major to save people updating and it breaking their old and busted software) and tell people they need node 8+ or whatever the dependency requirement is for this. Also update Travis to use 8+

**Comment by stefanosala** [comment]
@RickCraig yeah, this package definitely needs some love

**Comment by stefanosala** [comment]
@RickCraig we should probably just deprecate it in favour of https://github.com/woocommerce/wc-api-node#readme . What do you think?

**Comment by RickCraig** [comment]
That one was last updated 3 years ago, but yeah I guess seeing it has a lot more installs, stars etc, it's clearly the more popular one and it is built by woocommerce themselves. I'm for a deprecation 👍

**Pull request merged**
